sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t saranraju90/dockerrecattest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saranraju90/dockerrecattest npm test -- --coverage

after_success:
  - docker build -t saranraju90/multi-client ./client  
  - docker build -t saranraju90/multi-nginx ./nginx
  - docker build -t saranraju90/multi-server ./server  
  - docker build -t saranraju90/multi-worker ./worker  

 #  LOG into docker CLI  

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # take thode images and push them to dockerHUB

  - docker push saranraju90/multi-client
  - docker push saranraju90/multi-nginx
  - docker push saranraju90/multi-server
  - docker push saranraju90/multi-worker

